"""change start and end time data types

Revision ID: 4adbf72c3f95
Revises: 946d53947188
Create Date: 2024-06-25 10:59:06.218332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4adbf72c3f95'
down_revision = '946d53947188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.TIME(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.String(),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.String(),
               type_=sa.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
