"""update teacher model

Revision ID: 946d53947188
Revises: 0f350aa5be13
Create Date: 2024-06-25 10:12:21.498349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946d53947188'
down_revision = '0f350aa5be13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('username')
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
